"""Held-out passages for the depth layer: one fresh passage per kind, written after the lenses were tuned on
tests/passages.py, on subjects far from those passages, so the lenses are measured on speech they were not fitted to."""
HELDOUT = [
 ('instruction', "Start by loosening the two bolts on the bicycle seat. Then slide the seat up until your leg is almost straight at the bottom of the pedal. Make sure the nose of the seat points forward, and tighten both bolts again before you ride."),
 ('lecture', "In this talk I will examine how cities managed water before modern plumbing. The evidence from Roman aqueducts suggests a remarkable grasp of gradient. Scholars have argued that these systems shaped settlement for centuries, and the findings from recent excavations support that theory."),
 ('lesson', "Okay everyone, let's look at this map together. Who can find the river on the left? Good. Now with your partner, trace where the river meets the sea. What do you notice about the towns along it? Try the next map on your own."),
 ('dialogue', "Are you coming to the market tomorrow? I might, why? Because I need help carrying the flour. Oh, I see. What do you think, eight o'clock? I agree, but can we make it nine? Fine, nine it is."),
 ('reflective monologue', "I remember the summer my father taught me to swim in the cold lake. At the time I felt only fear. Looking back, I realize he was showing me how to trust the water, and I have come to see that it taught me how to trust him."),
 ('thinking aloud', "Hmm, where did I put the receipt? Let me think. Maybe it's in the car. Wait, no, I cleaned the car yesterday. What if it fell into the recycling? Actually, let me check the coat pocket first, that's more likely."),
 ('stream of consciousness', "The kettle is singing and the radio says rain and I keep thinking of the attic, the box of letters, and my brother's handwriting, and the bus outside hisses, and the light is grey and soft like the inside of a shell, and always the clock."),
 ('reading aloud', "Chapter one. The village lay in a fold of the hills, its houses turned away from the road as if in disapproval of travellers. It was the custom of its people, however hospitable they may have been in private, to receive strangers with a considerable reserve."),
 ('song', "Everybody clap now, one two, la la la, sing it out, hey hey, bring the chorus round once more, one more time now, everybody sing, la la la, and the chorus comes again, sing it loud together, hey hey."),
 ('lyrics', "Tonight the city lights are calling you, calling you, and I'm still waiting at the station. You're the one I'm dreaming of, baby, every time the train goes by, every time I close my eyes, I'm still calling you."),
 ('poetry', "The heron is a grey hinge on the marsh; it opens, and the morning swings through. Beneath its wings the reeds bow down like scholars, and the water, that patient mirror, keeps the sky folded in its silver pocket."),
 ('story', "Once there was a fisherman who lived at the edge of a cold sea. One night he heard a voice beneath the waves. He rowed out past the rocks, past the lighthouse, and found a lantern floating on the water. At last he carried it home, and from then on his nets were never empty."),
 ('character development', "He had always been proud, and his pride kept him alone. But when the flood came he was forced to ask his neighbours for help. Slowly his stubbornness gave way to gratitude, and by the end of the year he had become the first to offer a hand."),
 ('scenery', "Below the ridge the meadow lay wide and golden, and a silver stream wound through the grass toward the forest. A thin mist rose from the hollows, the far hills turned blue in the evening light, and somewhere a dog barked, and the smell of cut hay drifted up."),
 ('lore', "Among the river clans, the house of the ferrymen keeps the oldest oath. By custom no boat may cross at dawn without a word to the ancestors, and every ferryman traces his lineage to the founders who first bound the river with rope."),
 ('myth', "In the beginning the moon lived on the earth and walked among the animals. Then the raven tricked her into climbing the tallest tree, and she rose into the heavens and could not return. That is why the moon watches us every night, and why the ravens laugh at dusk."),
 ('cosmology', "Every star we see is a furnace where atoms are forged. When the largest stars collapse, they scatter carbon and iron across space, and new planets gather from that dust. The universe is still expanding, and we are made of the matter it has been cooking for billions of years."),
 ('mystery', "The window was shut, yet the candle had gone out. Who could have entered the study? The housekeeper swore she had locked the door, and the gardener had an alibi. But someone had moved the ledger, and a single wet footprint pointed toward the cellar."),
 ('argument', "My claim is simple: cities should plant more trees. The evidence is clear, because shaded streets are cooler, cleaner and safer. Critics say the cost is too high, but every tree returns its price in lower energy bills. Therefore we must plant them now."),
]
